# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6a1fc59c29c7b7a56a96ed7ab3c01f9"
name = "EpicOrderFulfill"
handle = "epic-order-fulfill"
application_url = "https://regarded-op-e-glenn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_assigned_fulfillment_orders,write_customers,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://regarded-op-e-glenn.trycloudflare.com/auth/callback",
  "https://regarded-op-e-glenn.trycloudflare.com/auth/shopify/callback",
  "https://regarded-op-e-glenn.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
